### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by neeharv** [sajari/sajari-sdk-js#11]
Following convention, the SDK could check if the success / callback functions were passed down, or else return a `Promise`.

This makes the sdk super useful on node.js as well.

On a side-note, in node the convention is to have a callback passed as a `fn(error, result)`, and as the last param. Since this doesn't adhere to that, we can't use methods like `bluebird.promisifyAll` to convert this callback based lib to a promise based one.

**Comment by tbillington** [comment]
That's a good suggestion @neeharv . I'm in the middle of writing an updated version of this sdk, and it will be broken into a node and browser versions. The node version will use gRPC and I'll definitely look into promises for making that nice.

I'm aiming for older browser compatibility and small library size for the browser version, so I'll be weighting up those kinds of nice features vs size.

**Comment by tbillington** [comment]
I've adopted the node callback style in the api response, and the node version will probably use promises. Thanks for your comments @neeharv :)
