### ISSUE TITLE
Refactor fieldFilter to remove constants.

### ISSUE THREAD

**Issue by dhowden** [sajari/sajari-sdk-js#18]
Instead allow things like:

```lang=javascript
fieldFilter('event', '=', '100')
```

Could we even make this:

```lang=javascript
fieldFilter('event =', '100')
```

The full set of operations would include `^` (prefix), `$` (suffix), `~` (contains), `!~` (not contains).

**Comment by tbillington** [comment]
Fixed in https://github.com/sajari/sajari-sdk-js/commit/5aa884412bca81cd3e80752d09dbf25ac4c4dfa1
