### ISSUE TITLE
There is no working documentation for the SDK.

### ISSUE THREAD

**Issue by guryanov-a** [sajari/sajari-sdk-js#27]
I can't find working documentation for the SDK: https://doc.esdoc.org/github.com/sajari/sajari-sdk-js/ from README.md gives `403 Forbidden`.

**Comment by tbillington** [comment]
Tried to resolve this upstream but no dice: https://github.com/esdoc/esdoc-hosting/issues/20.

Thanks @guryanov-a you can now find them at https://sajari.github.io/sajari-sdk-js/.
