### ISSUE TITLE
Maintenance of actual tags and releases on GitHub.

### ISSUE THREAD

**Issue by guryanov-a** [sajari/sajari-sdk-js#28]
Could you please create and maintain actual tags and releases on GitHub (sync with the version that is placed on NPM)? It's confusing now.

**Comment by tbillington** [comment]
The current tag in the repo is now in sync with NPM. Thanks for reporting this!

Just to help us understand, do you use git tags instead of NPM versions to reference the package in your application?

**Comment by guryanov-a** [comment]
@tbillington Thank you for the quick response and fixes.
Usually, I use the latest NPM version, but, as I remember, I needed to use version 15.4.0 instead of 16.0.0 (it was the latest) for avoiding incompatibilities when I was trying React SDK because the 15.4.0 version was peer dependency for the React SDK. In such cases, I install the specific version from the GitHub (maybe I can do that also with NPM, I need to check the documentation better).

**Comment by tbillington** [comment]
Ah, I see.

You can set the version explicitly in `package.json` eg `"sajari": "15.4.0"`. Hope that helps.
