### ISSUE TITLE
Remove need for OPTIONS pre-flight

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-js#36]
This causes a delay on the first key-press for a user. See https://stackoverflow.com/questions/29954037/why-is-an-options-request-sent-and-can-i-disable-it

Likely cause we send the `Content-Type: application/json` header, which is not allowed. Only the following are allowed for the `Content-Type` header: 

- application/x-www-form-urlencoded
- multipart/form-data
- text/plain

**Comment by benhinchley** [comment]
This has been resolved
